# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
name: tensorflow-roadsigns-yolo
channels:
  - defaults
dependencies:
  - autopep8
  - bottleneck
  - click>=7.1.*,<8.0 # mlflow/prefect requirement
  - cloudpickle>=1.3.0 # prefect requirement
  - cryptography=3.*
  - cython
  - dask>=2.17.0 # prefect requirement
  - docker-py>=4.0.0 # mlflow requirement
  - entrypoints # mlflow requirement
  - flake8>=3.8.0
  - gitpython>=2.1.0 # mlflow requirement
  - gunicorn # mlflow requirement
  - ipython
  - isort>=5.6.0
  - jedi
  - jinja2>=2.11.0,<3
  - joblib
  - jupyter
  - jupyterlab
  - lxml
  - markupsafe=2.0.1
  - matplotlib
  - mkl
  - nodejs
  - nose
  - numexpr
  - numpy>=1.18.0 # adversarial-robustness-toolbox requirement
  - packaging=20.* # mlflow requirement
  - pandas>=1.1.0
  - pillow
  - pip
  - protobuf>=3.7.0 # mlflow requirement
  - psutil
  - psycopg2
  - pytables
  - python-dateutil>=2.8.0 # prefect requirement
  - python=3.9.*
  - pytz>=2018.7 # mlflow requirement
  - pyyaml=5.3.1 # mlflow requirement
  - redis-py>=3.2.1 # prefect requirement
  - requests>=2.25.0
  - scipy>=1.4.1 # adversarial-robustness-toolbox requirement
  - scikit-learn>=1.0.0,<1.1.0
  - simplejson
  - six # adversarial-robustness-toolbox requirement
  - sqlalchemy # mlflow requirement
  - sqlparse>=0.3.1 # mlflow requirement
  - pip:
      - -e ../../.
      - adversarial-robustness-toolbox==1.9.*
      - alembic<=1.4.1
      - black>=20.8b1,<22
      - boto3 # mlflow requirement
      - databricks-cli>=0.8.7 # mlflow requirement
      - flask-accepts>=0.17.0,<1
      - Flask-Injector>=0.12.0,<1
      - Flask-Migrate>=2.5.0,<3
      - flask-restx>=0.2.0,<1
      - Flask-SQLAlchemy>=2.4.0,<3
      - Flask-WTF>=0.14.3,<1
      - Flask>=1.1.0,<2 # mlflow requirement
      - gorilla
      - imgaug>=0.4.0,<1
      - marshmallow>=3.9.0,<4
      - mlflow>=1.12.0,<2
      - multimethod>=1.5
      - mypy>=0.920
      - passlib
      - prefect>=1.0.*,<1.1.0
      - prometheus-flask-exporter # mlflow requirement
      - pyarrow>=2.0.0
      - pycocotools
      - pycodestyle
      - pydocstyle
      - python-json-logger>=2.0.0
      - querystring-parser # mlflow requirement
      - rich>=9.1.0
      - rq>=1.5.0
      - structlog>=20.2.0
      - tensorflow>=2.8.0,<2.9.0
      - typing-extensions>=3.7.4.0
      - werkzeug>=1.0.0,<2
