[global]
disableWatchdogWarning = false
showWarningOnDirectExecution = true
dataFrameSerialization = "arrow"

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[client]
caching = true
displayEnabled = true
showErrorDetails = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true

[server]
folderWatchBlacklist = []
fileWatcherType = "auto"
headless = true
runOnSave = false
address = "0.0.0.0"
port = 8501
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[mapbox]
token = ""

[deprecation]
showfileUploaderEncoding = "True"
showImageFormat = "True"
showPyplotGlobalUse = "True"

[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
#base =

# Primary accent color for interactive elements.
#primaryColor =

# Background color for the main content area.
#backgroundColor =

# Background color used for the sidebar and most interactive widgets.
#secondaryBackgroundColor =

# Color used for almost all text.
#textColor =

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
